# Generated by Django 4.2.1 on 2023-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='occupant',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='occupant',
            name='nickname',
            field=models.CharField(default=None, max_length=127),
        ),
    ]
