# Generated by Django 4.2.1 on 2023-05-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0002_occupant_age_occupant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
