# Generated by Django 4.2.1 on 2023-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0003_alter_occupant_age_alter_occupant_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='page_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
