# Generated by Django 4.2.1 on 2023-05-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0006_occupant_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
