# Generated by Django 4.2.1 on 2023-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0008_alter_hobby_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='owner',
        ),
        migrations.AddField(
            model_name='occupant',
            name='hobbies',
            field=models.ManyToManyField(related_name='hobbies', to='murino.hobby'),
        ),
    ]
