# Generated by Django 4.2.1 on 2023-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0009_remove_hobby_owner_occupant_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.CharField(default=None, max_length=127),
        ),
    ]
