# Generated by Django 4.2.1 on 2023-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0010_hobby_description_hobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
