# Generated by Django 4.2.1 on 2023-10-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murino', '0012_remove_hobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.CharField(default=None, max_length=127),
        ),
    ]
